### ISSUE TITLE
Testes da 3ª fase do Certame: habilitação de currículos, memorial descritivo e plano de intervenção.

### ISSUE THREAD

**Issue by rmadev-master** [EscolaDeSaudePublica/SACS#15]

**Comment by rmadev-master** [comment]
**Última atualização:** http://10.17.0.68/espce/p-sacs/commit/9630360261894053a3c39703bb92736948a42fd5

**Comment by rmadev-master** [comment]
**Atualização em 27/02/2020, 14h16min**: http://10.17.0.68/espce/p-sacs/commit/529bd8eff4d6a34f2bbd22fe86e21e6c7ba97eb7

**Comment by Junior-Shyko** [comment]
http://10.17.0.68/espce/p-sacs/commit/2547fc8cf4cfde97656b9e1cc13b9bf3e1075e93

**Comment by Junior-Shyko** [comment]
http://10.17.0.68/espce/p-sacs/commit/ae53c774be173b1d8cc0c0f52e8907f92bdeda5f

**Comment by rmadev-master** [comment]
@Junior-Shyko , por favor:

- [ ] Relatórios até o final: adicionar 3º filtro em todos os relatórios administrativos.
- [ ] Relatórios extra: adicionar dois relatórios no admin, da 1ª etapa, classificados e classificáveis, somente com o terceiro filtro (cargo).
- [ ] Plano de Intervenção: adicionar segunda etapa da avaliação/pontuação da banca, onde vai atualizar somente a nota final.
- [ ] Adicionar a 3ª etapa: entrevista, somente pontuar. Só serão entrevistados (lembrar no relatório final da 2ª etapa) os 05(cinco) primeiros colocados para cada cargo (3º filtro).

**Comment by rmadev-master** [comment]
Em andamento.

**Comment by rmadev-master** [comment]
**Última atualização:** http://10.17.0.68/espce/p-sacs/commit/9640a2d77b2105664d00f5218306d0f2f14e8540
