### ISSUE TITLE
Análise do Edital

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/SACS#150]
Inscrições a partir de: **01/10/2020**

[Versão atual :arrow_down:](https://github.com/EscolaDeSaudePublica/SACS/files/5299928/edital_14.pdf)

- **Calendário:** [clique aqui](https://github.com/EscolaDeSaudePublica/SACS/files/5299953/calendario.pdf)
- **Isenções:** Sim
- **Perfis e Atribuições:** [clique aqui](https://github.com/EscolaDeSaudePublica/SACS/files/5299966/perfis.pdf)
- **Etapa Única:** [clique aqui](https://github.com/EscolaDeSaudePublica/SACS/files/5299985/etapa.pdf)
- **Pontuação 1º Momento:** [clique aqui](https://github.com/EscolaDeSaudePublica/SACS/files/5300163/pontuacao1.pdf)
- **Pontuação 2º Momento:** [clique aqui](https://github.com/EscolaDeSaudePublica/SACS/files/5300000/pontuacao2.pdf)
- **Desempate:** [clique aqui](https://github.com/EscolaDeSaudePublica/SACS/files/5300010/desempate.pdf)

**Histórico de Editais**

28/09/2020: [1ª versão](https://github.com/EscolaDeSaudePublica/SACS/files/5299928/edital_14.pdf)

**Dados do sistema:**

**Home:** edt142020cevig
**Bolsa(s):** Banco de Colaboradores
**Controle de Vagas:** 5
**Validade:** 01 ano (+ 01 renovação)
**E-mail:** edt142020@esp.ce.gov.br
**Valor das Inscrições:** R$ 100,00 (cem reais)

**Leis isenções:** 1,2,3,4

**Atendimento Especial:** formulário no sistema (padrão)
**Solicitação de Isenção:** Se aplica
**Requerimento de Nome Social:** não citado
**Comprovação de Jurado:** formulário no sistema (padrão)
**Etapas:** 01 com 02 momentos -> **Habilitação de Currículo**  e **Plano de Trabalho:**
**Habilitação de Currículo:** total de **10 pontos**, **mínimo de 6 pontos**, 60%
**Plano de Trabalho:** total de **10 pontos**, **mínimo de 6 pontos**, 40%
**Média Final:** ((N1E x 6) + (N2E x 4))/10

**Desempate 1ª Nota:** nota
**Desempate 2ª Nota:** nota

**Desempate Resultado Final:** 60 anos, nota 1º momento, maior idade, jurado.
**Filtros:** 02
**Quadros de Pontuação 1º Momento:** 7
**Quadros de Pontuação 2º Momento:** 1
**Recursos:** sistema
**Lattes:** obrigatório
**Link do Trello:** [clique aqui](https://trello.com/c/SZXiGLrd/40-edital-14-2020-cevig-bolsa-ext-tecnol%C3%B3gica-qualifica%C3%A7%C3%A3o-em-vigil%C3%A2ncia-%C3%A0-sa%C3%BAde)

**Comment by victorMagalhaesPacheco** [comment]
@rmadev-master estamos na dúvida referente a quantidade de perfis no primeiro momento.

**Comment by Junior-Shyko** [comment]
Adicionado o link da corrigenda.
