### ISSUE TITLE
Gerar lista de emails dos inscritos no edital 16/2020

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/SACS#161]

**Comment by Junior-Shyko** [comment]
Como relatório em PDF ou simplesmente na página no área administrativa?

**Comment by victorMagalhaesPacheco** [comment]
> Como relatório em PDF ou simplesmente na página no área administrativa?

Pelo banco.

**Comment by victorMagalhaesPacheco** [comment]
Finalizado.
