### ISSUE TITLE
Ajustar o Edital 02/2020, usando o 01/2020 como base.

### ISSUE THREAD

**Issue by rmadev-master** [EscolaDeSaudePublica/SACS#19]

**Comment by rmadev-master** [comment]
Ajustes concluídos por @Junior-Shyko .

**Comment by helenhilario** [comment]
Reunião realizada com sucesso! Ver registro e encaminhamentos na **Ata Permanente** https://docs.google.com/document/d/198nsIKofrEHpE1nAUA_RbRG7RayZE7yKDjIY0BZmPcg/edit#
