### ISSUE TITLE
Organizar e Testar o sistema para publicação.

### ISSUE THREAD

**Issue by rmadev-master** [EscolaDeSaudePublica/SACS#59]

**Comment by Junior-Shyko** [comment]
- Criado um arquivo para funcoes de forma geral e modificado o alerta antes das inscrições [5b743913](http://10.17.0.68/espce/p-sacs/commit/edd3cdc5e31045f750240c7febb22219111d72ca)

**Comment by Junior-Shyko** [comment]
**Adicionado o nome social do candidato** - [81b27240](http://10.17.0.68/espce/p-sacs/commit/81b27240272ce275c2812b2bf5efcbbd1e941e01)

**Comment by rmadev-master** [comment]
Concluído.
